### PR TITLE
29-01-22 Filling in missing english strings

### PR DESCRIPTION
**Pull request by Kazemeka**
All marked strings have been filled. 

Oksana is still being worked on. There are various Russian texts hidden in-between English text. The hunt for those goes on.

Credits: Kazemeka, Fignuts

P.S. For the love of God, do not change ATP to MTP. It's so incorrect. ATP is a correct transliteration, MTP is something completely crazy.

### CODE REVIEW

**Comment by jarni-ua** [comment]
Have you been here http://stalker-worlds.ru/forum/topic/10514-english-translation-specifics/ ?
@KrechetSt  does most of the English translation now. It would be really nice if you contact each other and plan your work together to avoid conflicts.
In any case I appreciate your effort.

**Comment by Kazemeka** [comment]
I have spoken with both Krechet and Winsor. Winsor gave the go, while Krechet was less than eager to work together. 

Since the community needs the translation _now_, me, fignuts and PillWet have worked for the past two weeks on filling in the gaps and making OP-2.2 actually playable. We are only missing the oksana files. Everything else is 100% playable.

My suggestion is to merge our work with Krechet's, with the latter being given priority, if the texts contain the updated information.

**Comment by Kazemeka** [comment]
Any update?

**Comment by jarni-ua** [comment]
I'll merge it. Need to solve conflicts first though.

**Pull request merged**
